version: '3.7'
services:
  db:
    image: postgres:12.0-alpine
    ports:
      - '54320:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=db